# Tensorflow
**Question** : What is tensorflow?
- From programming perspective a tensor is a multidimensional array that has the ability to be run on the gpu.  
- From mathematical perspective, a tensor is a generalization of a scalar, vector and matrix. For example, a vector is a one dimensional tensor and a matrix is a two dimensional tensor.


In [4]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'  # To hide error message
import tensorflow as tf

### Initialization


In [5]:
 x=tf.constant(4)
 print(x)

tf.Tensor(4, shape=(), dtype=int32)


a scalar value having no shape. datatype by default is set to int32. we can set the shape and the dtype of the tensor by following piece of code

In [8]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)

In [9]:
x=tf.constant([[1,2,3],[4,5,6]]) # two dimensional matrix
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [13]:
x=tf.zeros((2,4))
print(x)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)


In [15]:
x=tf.eye(3) # identity matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [17]:
# distribution
x=tf.random.normal((3,3),mean=0,stddev=1) # normal distribution
print(x)


tf.Tensor(
[[-0.4021154   0.32953298 -1.5498751 ]
 [-0.44190416  0.25271016 -0.6416836 ]
 [ 0.8624003   0.19016981  0.21101798]], shape=(3, 3), dtype=float32)


In [19]:
# uniform distribution
x=tf.random.uniform((2,3),minval=0,maxval=1)
print(x)

tf.Tensor(
[[0.2825092  0.20178056 0.12459147]
 [0.40718126 0.6119164  0.13420379]], shape=(2, 3), dtype=float32)


In [22]:
x=tf.range(start=1,limit=10,delta=2)
print(x)
#cast is a way to conversion between different types
x=tf.cast(x,dtype=tf.float32)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)


### Mathematical operations


In [23]:
#two vectors
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
a=tf.add(x,y)
s=x-y  # or tf.subtract(x,y)
m=x*y # or tf.multiply(x,y)
d=x/y  # or tf. divide(x,y)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)


these arithmatic operations are performed element wise. we can do dot product of the two vectors. dotproduct of two vectors=sum of elementwise mutiplications which is a scalar value.

In [28]:
dot_product=tf.tensordot(x,y,axes=1)
print(dot_product)
dp=tf.reduce_sum(x*y)
print(dp)

tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)


In [29]:
#exponentiation
exp_x=x**3
print(exp_x)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [30]:
#matrix multiplications 
'''remember that, for matrix multiplications column of first matrix should be 
equal to the row of second matrix'''
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
print(z)
#another way
m_mul=x@y
print(m_mul)

tf.Tensor(
[[ 1.1437747   0.525156   -1.0739632  -1.5999595 ]
 [ 2.909784   -0.58547074 -1.40404    -2.2411978 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 1.1437747   0.525156   -1.0739632  -1.5999595 ]
 [ 2.909784   -0.58547074 -1.40404    -2.2411978 ]], shape=(2, 4), dtype=float32)


### Indexing

for a vector

In [32]:
# for a vector
x=tf.constant([1,2,3,5,4,6])
print(x[:]) # print all elements same as print(x)
print(x[1:])# print all from index 1
print(x[1:2]) #only one element at index 1
print(x[::2]) # starting from index 0 and print every other element
print(x[::-1])# print all elements in reverse order

tf.Tensor([1 2 3 5 4 6], shape=(6,), dtype=int32)
tf.Tensor([2 3 5 4 6], shape=(5,), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor([1 3 4], shape=(3,), dtype=int32)
tf.Tensor([6 4 5 3 2 1], shape=(6,), dtype=int32)


In [33]:
# print by passing a array of indices
indices=tf.constant([0,3])
x_ind=tf.gather(x,indices)
print(x_ind)

tf.Tensor([1 5], shape=(2,), dtype=int32)


for matrix

In [37]:
x=tf.constant([[1,2],[3,4],[5,6]])
print(x) # print all
print(x[:,0]) # print all row column 0
print(x[1,:]) # print all column in row 1
print(x[:2,:])# first two rows with every column

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor([1 3 5], shape=(3,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### Reshaping

In [38]:
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [39]:
x=tf.reshape(x,(3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [42]:
# transpose
x=tf.transpose(x,perm=[1,0]) 
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
